import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import schoolsRouter from "./schools";
import incidentsRouter from "./incidents";
import protocolsRouter from "./protocols";
import alertsRouter from "./alerts";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import delegatedRolesRouter from "./delegatedRoles";
import annexTemplatesRouter from "./annexTemplates";
import referralBodiesRouter from "./referralBodies";
import caseTasksRouter from "./caseTasks";
import messagesRouter from "./messages";
import sencoRouter from "./senco";
import behaviourRouter from "./behaviour";
import ptaRouter from "./pta";
import newsletterRouter from "./newsletter";
import dataRetentionRouter from "./dataRetention";
import diagnosticsRouter from "./diagnostics";
import diaryRouter from "./diary";
import teacherPostsRouter from "./teacherPosts";
import demoRouter from "./demo";

const router: IRouter = Router();

router.use(healthRouter);
router.use(newsletterRouter);
router.use(authRouter);
router.use(schoolsRouter);
router.use(incidentsRouter);
router.use(protocolsRouter);
router.use(alertsRouter);
router.use(notificationsRouter);
router.use(dashboardRouter);
router.use(delegatedRolesRouter);
router.use(annexTemplatesRouter);
router.use(referralBodiesRouter);
router.use(caseTasksRouter);
router.use(messagesRouter);
router.use(sencoRouter);
router.use(behaviourRouter);
router.use(ptaRouter);
router.use(dataRetentionRouter);
router.use(diagnosticsRouter);
router.use(diaryRouter);
router.use(teacherPostsRouter);
router.use(demoRouter);

export default router;
